### PR TITLE
Spark download fix

### PR DESCRIPTION
**Pull request by bpanneton**
Two commits to fix a download version and a classpath bug.

### CODE REVIEW

**Comment by chu11** [comment]
LGTM, thanks

**Comment by bpanneton** [comment]
I don't see the commit 21943d0 in the repo for some reason? Was this missed?

**Comment by chu11** [comment]
Crud, I think I did a non-fast forward push yesterday.  My bad due to a cut & paste of git commands in my command history.

**Comment by bpanneton** [comment]
No worries! Looks good now!

**Pull request merged**
