### PR TITLE
Hbase 1.1.2

### PR DESCRIPTION
**Pull request by bpanneton**

### CODE REVIEW

**Comment by chu11** [comment]
Generally speaking looks good.  But

A) Could you rebase, so the netcat/Zookeeper patch isn't in this pull request
B) could the changes to the magpie-apache-download-and-setup.sh be in a separate patch since there are changes in there not related to hbase 1.1.2.
C) could you make a new commit/patch after this one be after you run 'make' in the script-templates directory so all the submission scripts are updated.
D) And slightly tweak the NEWS file ... it'll be obvious what to update :-)

**Comment by bpanneton** [comment]
Sure, once you merge the magpie-apache-download-and-setup.sh ill rebase again and make the changes.

**Comment by bpanneton** [comment]
Should be good now

**Comment by bpanneton** [comment]
Oh wait. Let me clean that up.

**Comment by bpanneton** [comment]
There we go.  : )

**Comment by chu11** [comment]
LGTM

**Pull request merged**
