### PR TITLE
Added initial thrift support

### PR DESCRIPTION
**Pull request by bpanneton**
Potential thrift support. I'm not sure if this is the best way to do it, but I manged to get it working. I was able to connect with happybase.

### CODE REVIEW

**Comment by chu11** [comment]
Overall looks fine, a few nits & issues.

1) Don't think you need a new variable "hbasewiththrift", I think the original is enough.  You might have been copying code that created new variables b/c of the need to add things into hbase-env.sh or hbase-site.xml.

2) Please add a check for correct input in magpie-check-inputs

3) Shouldn't there be something to shutdown the server when we tear down?

4) Instead of "HBASE_WITH_THRIFT" how about "HBASE_START_THRIFT_SERVER", since this is actually turning on a new server, it's not just another library/link/etc.

**Comment by bpanneton** [comment]
2) Please add a check for correct input in magpie-check-inputs
I didn't add anything to magpie-check-inputs because I wanted it to default to 'no' if the variable was not set. I can still add the default code into magpie-check-inputs but I didn't see you doing anything like that there.

I went ahead and made the changes as you described. Let me know if anything else should be changed.

**Comment by chu11** [comment]
Hey Brian, what I meant was a check like this:

```
if [ "${HADOOP_SETUP}X" != "X" ] \
    && ( [ "${HADOOP_SETUP}" != "yes" ] && [ "${HADOOP_SETUP}" != "no" ] )
then
    echo "HADOOP_SETUP must be set to yes or no"
    exit 1
fi
```

Just to make sure the input is "yes" or "no".  That way it doesn't matter if the user set the environment variable or not when you check for == "yes".  BTW, also noticed:

```
if [ ${HBASE_START_THRIFT_SERVER} == "yes" ]
```

for consistency to other code I think that should be quotes.

As for the shutdown code, shouldn't the hbase-daemon.sh call be before stop-hbase.sh?  I would think it should go before it.  But perhaps it's independent of the daemons launched by start-hbase.sh?  I really have no idea, it just looks peculiar.

**Comment by chu11** [comment]
LGTM

**Pull request merged**
