### PR TITLE
Added support for not reusing the hdfs directory

### PR DESCRIPTION
**Pull request by bpanneton**
I tested both ways (reusing paths and not reusing paths) and they seem to work fine. I think localonnetworkdrive support is good to merge with master.

### CODE REVIEW

**Comment by chu11** [comment]
Various nit changes listed above, but one overarching change I'd like to see is that the default is "no", because that will make backwards compatibility work for older Magpie scripts.

So instead of "REUSE_PATH" how about something like "NEW_INSTANCE" ... hmmm that's probably not that good.  Hmmm, can you think of a better variable name?  But like that.

**Comment by bpanneton** [comment]
The default should actually be 'yes' because you currently reuse the path. However I will try to think of a new name. I added your suggested fixes.

**Comment by bpanneton** [comment]
Could be ZOOKEEPER_REUSE_DATA_DIR and HADOOP_REUSE_HDFS_PATH?

**Comment by bpanneton** [comment]
Or maybe ZOOKEEPER_PER_JOB_DATA_DIR and HADOOP_PER_JOB_HDFS_PATH?

**Comment by chu11** [comment]
Oops, depends on the naming, I was probably thinking too far ahead.  But what I mean is that it should continue to use the original path by default.  The yes/no depends on what we name it of course.

I like the "PER_JOB_DATA" naming.  That makes it more clear.

As for recent patches, if you could make the commit log messages a little more clear, that'd be a good.  The thrift one also fixes a logic error in the magpie-check-inputs and the latter also adds the zookeeper equivalent.

**Comment by chu11** [comment]
One additional thought.  If the user specifies per job data ... do we want to automatically delete the data for them when the job is done???

Arguments for yes and no.  If no, it should be documented in the submission scripts.

**Comment by chu11** [comment]
One other thing.  Since the hbase thrift check fix is independent of this pull request, could you make that a different pull request?  I can merge it in immediately.

**Comment by bpanneton** [comment]
I'll make the thrift one an independent pull. I'll also change to PER_JOB_DATA. I would say we don't delete the data in case you want to reuse it again. That was why I originally called it REUSE. My thought is that you would run the first job. Then you could come back and rerun queries on the same hbase dataset. But this would allow you to run two separate jobs in parallel on different datasets as well.

**Comment by bpanneton** [comment]
Perhaps this should be called REUSE_JOB_DATA instead? and REUSE_JOB_HDFS_PATH?

**Comment by chu11** [comment]
The main thing is I would like the original behavior (reusing) to the be default.  So users should have to specify a new configuration to get different behavior.  So I think it might be better to do the "per_job" config instead.

**Comment by bpanneton** [comment]
Yes, the original behavior is currently the default in the patches that I have provided. I will name it PER_JOB.

**Comment by bpanneton** [comment]
I think this should be good to merge now. I renamed them all as requested.

**Comment by chu11** [comment]
overall looks good, just some nits.  One final nit though, can you re-make the script templates so all the new additions are added into the submission scripts.

**Comment by bpanneton** [comment]
Hows that?

**Comment by chu11** [comment]
just one typo, which of course propagated during the make.  Sorry if the typo was due to my prior comment.

**Comment by bpanneton** [comment]
Fixed! Should be good to go now!

**Pull request merged**
